### ISSUE TITLE
Add an URL organization repo of an existing PA

### ISSUE THREAD

**Issue by LorenzoS92** [italia/developers-italia-api#115]
Add Code field in Publishers to uniquely identify one PA 
Implement API (PUT or GET + PATCH or POST) to add an URL of an existing PA

**Comment by bfabio** [comment]
Name ideas:
- alternativeCode
- additionalId
- externalCode

**Comment by LorenzoS92** [comment]
At the end, the better solution also to keep compatibility and avoid PUT incorrect behaivour, is to do a GET and after a PATCH (or POST).

the field name will be externalCode
