### ISSUE TITLE
Wrong "primarykey" key in db models definitions 

### ISSUE THREAD

**Issue by LorenzoS92** [italia/developers-italia-api#128]
All models have the "primarykey" defined incorrectly.
It should be defined as "primaryKey".

We should update those models and update tests accordingly:
* Software
* SoftwareURL
* Webhook
* Event
* Bundle

**Comment by bfabio** [comment]
Looks like [GORM tags are case insensitive](https://gorm.io/docs/models.html#Fields-Tags) after all
