### ISSUE TITLE
Validation errors should be clearer

### ISSUE THREAD

**Issue by bfabio** [italia/developers-italia-api#166]
The validation errors in responses should be clear enough to understand what the error is.

Right now they look like this:

```json
{
  "title": "can't create Publisher",
  "detail": "invalid format",
  "status": 422,
  "validationErrors": [
    {
      "field": "alternativeId",
      "rule": "min"
    }
  ]
}
```

which doesn't clarify what the problem actually is (it's `alternativeId` not being long enough - in this case it was an empty string).

We should probably map go-validator's rules to something human readable as we do in https://github.com/italia/publiccode-parser-go/blob/2c75f653507ca718c3d36dc2842d20474b5f3ca0/parser.go#L236, for example.

**Comment by inomag** [comment]
He, can I work on this?

**Comment by bfabio** [comment]
Also, we should probably return the original value that caused the error as well.

**Comment by Bavuett** [comment]
Hi @bfabio. I've just discovered this project while browsing GitHub and I'd like to help. I've read some of the Source Codes of the project and it seems that to solve this issue I'd have to focus on this particular [file](https://github.com/italia/developers-italia-api/blob/main/internal/common/validator.go), am I right?

**Comment by bfabio** [comment]
Hello @Bavuett and thank you! :wave: 

You're right, that structure [is created here](https://github.com/italia/developers-italia-api/blob/main/internal/common/validator.go#L52-L56), then serialized to JSON. 

Something like this would be ideal:

```json
{
  "title": "can't create Publisher",
  "detail": "invalid format: alternativeId is too long",
  "status": 422,
  "validationErrors": [
    {
      "field": "alternativeId",
      "value": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-very-long-alternative-id"
    }
  ]
}
```
where the `detail` field explains the error and with no `rule` field (that's a confusing field).

this way it's still compliant to [`application/problem+json`](https://www.rfc-editor.org/rfc/rfc7807). 

You can find the [validations we are doing on requests here](https://github.com/italia/developers-italia-api/blob/main/internal/common/requests.go) looking for the `validator` struct tag (we use [go-playground/validator](https://github.com/go-playground/validator)).

**Comment by Bavuett** [comment]
Alright. I'll begin working on this as soon as I have some spare time. Thanks!
