### ISSUE TITLE
Improvements of exposed data

### ISSUE THREAD

**Issue by claudiu-cristea** [italia/developers-italia-api#215]
I'm missing some information that allows me to fully understand an entry from https://api.developers.italia.it/v1/software:

## The code platform

In the case of self-hosted GitLab or Bitbucket software it's difficult to understand the underlying technology. Is it GitLab or Bitbucket? What API should I use if I want to fetch more info about that project? This info is not part of `publiccodeYml` blob either. But https://github.com/italia/publiccode-crawler knows this information and it would be nice to be exposed on the same level as `id`, `url`, `publiccodeYml `, etc. For instance:

```json
{
  "data": [
    {
      "id": "9c07d69d-f66e-44b7-93ff-f19509e47dcf",
      "platformType": "gitlab",
      "url": "https://riuso.comune.salerno.it/root/simel_2.git",
      ...
    },
    ...
  ],
  ...
}
```
Of course, `platformType` could be any of `github`, `gitlab`, `bitbucket`.

## The project's full path

Let's take an hypothetical case, a GitLab self-hosted project having this URL: https://example.com/base/path/group1/group2/group3/project.git. Note that the GitLab instance is installed at https://example.com/base/path (in a subdirectory, relative to the domain).

If a consumer of  https://api.developers.italia.it/v1/software API wants to understand which is the project full path (namespace and project), by extracting it from the URL, they will fail. That's because extracting the path is misleading. Most probably they will assume that everything that comes after the host is the project full path:

- namespace:  `base/path/group1/group2/group3`
- project name: `project`

But this is wrong as the project's namespace is `group1/group2/group3`. Again, this information is missed also from `publiccodeYml` blob. 

I think this info should be exposed. something like:

```json
    {
      "id": "9c07d69d-f66e-44b7-93ff-f19509e47dcf",
      "fullPath": "group1/group2/group3/project"
      "url": "https://example.com/base/path/group1/group2/group3/project.git",
      ...
    },
 ```

Moreover, this info is already available and exposed, as I see, by the `/software/{softwareId}/logs` path. In this way, a consumer understands how to derive the base URL of the GitLab/Bitbucket self-hosted platform.

**Comment by claudiu-cristea** [comment]
@bfabio,

Thank you for reply. Few remarks:

I was looking to https://github.com/alranel/go-vcsurl and that I'm thinking on very similar approach in order to guess the API from the URL. Given all your points, I understand that, exposing the _API type_, will not going to be supported here. I see most of them valid points. Maybe some are debatable but, yes, that's it, I can live with maintaining my own API guesser.

I was looking at the code from https://github.com/alranel/go-vcsurl (though I have _zero_ Go knowledge) but I can't find an answer to my 2nd point: _detecting the code hosting platform URL_. Or the other way around: _detecting the project full-path out of the full URL_. Of course, I'm referring to the situation when a GitLab instance is located not on the host root, but in a subdirectory.

**Comment by bfabio** [comment]
> I was looking at the code from https://github.com/alranel/go-vcsurl (though I have _zero_ Go knowledge) but I can't find an answer to my 2nd point: _detecting the code hosting platform URL_. Or the other way around: _detecting the project full-path out of the full URL_. Of course, I'm referring to the situation when a GitLab instance is located not on the host root, but in a subdirectory. It seems to me that the code assumes that the code platform is installed directly under the host (which, I agree, are most of the cases). Maybe I'm missing something?

@claudiu-cristea  you're spot on about `go-vcsurl` and `publiccode-crawler` currently assuming the code platform is right under the host. This is due to historical and practical reasons: namely, we never had to deal with that scenario :)

The thought was to potentially extend go-vcsurl or a similar library to manage these cases. It doesn't have to be go-vcsurl specifically; another library could work just as well. The key is to centralize the logic for detecting platform URLs and extracting project paths, making it more adaptable to different setups.

I'm not an expert with PHP, but I think there is a way to load a Go library and call it with FFI?

**Comment by claudiu-cristea** [comment]
@bfabio, thank you for clarifying and sorry for late feedback

We took a slightly different approach because we're using _code hosting platform plugins_ (e.g. [GitHub plugin](https://git.fpfis.tech.ec.europa.eu/ec-europa/digit-joinup-reference/-/blob/eu-oss-uat/web/modules/custom/eu_oss_catalogue/src/Plugin/eu_oss_catalogue/HostingPlatform/GitHub.php)). So each plugin _knows_ to determine if they are in business of handling a given URL. Then we're caching the result so next time we know which API to use.

Solved also the "GitLab installed under a sub-dir" by performing some [additional HTTP requests](https://git.fpfis.tech.ec.europa.eu/ec-europa/digit-joinup-reference/-/blob/eu-oss-uat/web/modules/custom/eu_oss_catalogue/src/Plugin/eu_oss_catalogue/HostingPlatform/GitLabSelfHosted.php#L97) but only when we have the non-standard case

Thank you again for support. Closing this issue

**Comment by bfabio** [comment]
@claudiu-cristea nice to know that approach makes sense, the plugins are kinda like [the scanners](https://github.com/italia/publiccode-crawler/tree/main/scanner) in `publiccode-crawler`
