### ISSUE TITLE
Make use of application/problem+json support in Gofiber

### ISSUE THREAD

**Issue by bfabio** [italia/developers-italia-api#225]
Gofiber [v2.51.0](https://github.com/gofiber/fiber/releases/tag/v2.51.0) added built-in support for application/problem+json, we should make use of it. Right now we manually add the header ourselves.

**Comment by richardrdev** [comment]
I can take a look at this, if nobody else is already

**Comment by bfabio** [comment]
@richardrdev it would be nice, thanks
