### ISSUE TITLE
Add search parameters to GET /logs

### ISSUE THREAD

**Issue by bfabio** [italia/developers-italia-api#236]
Add a `search` parameters to GET /logs, so consumers can search for errors or repos in the logs.

**Comment by k124k3n** [comment]
What kind of errors that you want consumers can search for? Error message?

**Comment by bfabio** [comment]
@k124k3n the [Log resource](https://developers.italia.it/it/api/developers-italia#model-Log) has a `message` field which is typically the output of our software crawler. It's a generic message, so you can find error messages or just plain informational logs in there.

A text search in that field would be enough, as consumer could search for anything they need, often times it's just about searching for all logs regarding a certain repository, which again would be listed in `message`.

**Comment by k124k3n** [comment]
Thank you. I can work on it.

**Comment by bfabio** [comment]
@k124k3n that's great, thanks!
