### ISSUE TITLE
Add a testing framework and a test suite

### ISSUE THREAD

**Issue by bfabio** [italia/developers-italia-api#29]
* Add a testing framework and a test suite
* Start unit testing

**Comment by LorenzoS92** [comment]
For unit testing we will use: https://github.com/stretchr/testify

**Comment by LorenzoS92** [comment]
For integration testing, Fiber suggest this:
https://docs.gofiber.io/api/app#test

What do you think? @bfabio , do you think that it's ok for int testing? We've to think how we can organize integration testing in the project (folder ecc)

**Comment by bfabio** [comment]
@LorenzoS92 it looks good and probably enough for our needs, let's try it out and see, we can always use something more sophisticated later if we need to.
