### ISSUE TITLE
Onboarding API & Model

### ISSUE THREAD

**Issue by LorenzoS92** [italia/developers-italia-api#41]
Generate the Onboarding API & relative models.

Inputs:
OrganizationID (ipa & others)
Url (Repository, that must be unique)
Email
Info (JSON)

The API will generate an UUID for every entry saved.

The API will initially allow to save PA that have completed the verification process from the onboarding platform.

**Comment by bfabio** [comment]
Depends on #12

**Comment by LorenzoS92** [comment]
At this moment, the "Info" field will be created later.
