### ISSUE TITLE
Review of API and OpenAPI

### ISSUE THREAD

**Issue by LorenzoS92** [italia/developers-italia-api#57]
Review the API architecture internally to asses security or performance concerns.

**Comment by bfabio** [comment]
@LorenzoS92 this is done, right?

**Comment by LorenzoS92** [comment]
Nope, not yet.
What we've to do:
1. Review API with OAS Checker
2. Update accordindly the OpenAPI and the API structure

**Comment by LorenzoS92** [comment]
Ok, if you want we can close this and keep the #90

**Comment by bfabio** [comment]
#90 is already resolved.

Keeping this one open is a matter of considering

> 2. Update accordindly the OpenAPI and the API structure

done or not
