### ISSUE TITLE
Add & fix tests

### ISSUE THREAD

**Issue by LorenzoS92** [italia/developers-italia-api#66]

**Comment by LorenzoS92** [comment]
* Update tests with validateFunc
* Function to clear Database in every tests
* Seed db?
* Other cleanup fixes

**Comment by bfabio** [comment]
Fixtures and database clearing implemented in https://github.com/italia/developers-italia-api/pull/75

**Comment by bfabio** [comment]
We have an acceptable infrastructure for tests now and the implemented endpoints use it. I'm closing it and add a new issue mentioning gabs.
